### ISSUE TITLE
library logo needs more while space around it

### ISSUE THREAD

**Issue by mizejewski** [ucsf-ckm/search.library.ucsf.edu#28]
Similar to logo seen at http://www.library.ucsf.edu/. Size can stay bigger if that's what we want, but it looks crowded at top and bottom. I tried fiddling with this, but I think I was conflicting with whatever you've already done to alter the defaults.

**Comment by Trott** [comment]
Fixed in 5bd91afc6c6f337cd20c561b1ec9f99ae2ee34d0
