### ISSUE TITLE
Did you mean?

### ISSUE THREAD

**Issue by Trott** [ucsf-ckm/search.library.ucsf.edu#3]

**Comment by Trott** [comment]
Did you mean functionality is implemented. Search for _medisine_ to see it in action. Link color and background color might not have sufficient contrast. Will open a ticket for an accessibility audit to find stuff like this. Would also be good to make sure that it is superior to the current results page in terms of accessibility. (I'm sure it is.)  /cc @mizejewski

**Comment by mizejewski** [comment]
@Trott  Awesome! Works for "acess medicine" and "cocrane" too. Agreed that colors need to be adjusted for accessibility. I'm working on some ideas for header/search layout and will consider that too.
